[package]
name = "feruca-benchmarks"
version = "0.1.0"
edition = "2024"

[dependencies]
feruca = { git = "https://github.com/theodore-s-beers/feruca" }
# feruca = { path = "../feruca" }
icu = "2.2.0"
icu_testdata = "1.5.0"

[features]
pipeline-stats = ["feruca/pipeline-stats"]

[dev-dependencies]
criterion = "0.8.2"

[profile.release]
debug = true
lto = true

[[bench]]
name = "destatis-de"
harness = false

[[bench]]
name = "met"
harness = false
